# Site info
site_name: PyCO2SYS
site_author: Matthew P. Humphreys
site_description: Marine carbonate system calculations in Python
copyright: Copyright &copy; 2020-2025 Matthew P. Humphreys (GNU GPLv3)

# Github repo info
repo_name: mvdh7/PyCO2SYS
repo_url: https://github.com/mvdh7/PyCO2SYS

# Navigation
nav:
  - Overview and installation: index.md
  - User guide:
      - Quick-start guide: quick.md
      - Arguments and results: detail.md
      - Adjust conditions (temperature and pressure): adjust.md
      - Uncertainty propagation: uncertainty.md
      - Advanced tips and tricks: advanced.md
      - Switching from v1 to v2: v1_to_v2.md
      - Validity range checker: validity.md
  # - API reference: api.md
  # - Validation: validate.md
  - References: refs.md
  - Version history: versions.md

# Appearance
theme:
  name: material
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: white
      accent: deep orange
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: orange
  font:
    text: Noto Sans
    code: Noto Sans Mono
  features:
    - navigation.footer
    - content.code.copy
    - navigation.expand
    - content.tooltips
  icon:
    annotation: material/plus-circle

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - tables
  - md_in_html
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css

# Plugins
plugins:
  - search
  # - mkdocstrings:
  #     handlers:
  #       python:
  #         options:
  #           docstring_style: numpy
