[build-system]
requires = [
    "setuptools",
]
build-backend = "setuptools.build_meta"

[project]
name = "PyCO2SYS"
description = "PyCO2SYS: marine carbonate system calculations in Python"
readme = "README.md"
requires-python = ">= 3.11"
dependencies = [
    "jax",
    "networkx",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Natural Language :: English",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Oceanography",
]
dynamic = ["version"]

[tool.setuptools.packages.find]
include = ["PyCO2SYS*"]

[tool.setuptools.dynamic]
version = {attr = "PyCO2SYS.meta.version"}

[tool.ruff]
line-length = 79

[tool.ruff.lint.isort]
combine-as-imports = true
force-single-line = false
lines-after-imports = 2
known-first-party = ["PyCO2SYS"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.pytest]
minversion = "6.0"
norecursedirs = [".*", "*.egg*", "build", "dist"]
testpaths = ["tests"]
python_files = ["test_*.py", "compare_*.py"]
