name: Run tests 
on:
  push:
    paths:
      - PyCO2SYS/**
      - tests/**
      - pyproject.toml
      - pytest.ini
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest xarray pandas openpyxl
        pip install .
    - name: Test with pytest
      run: |
        pytest
      env:
        JAX_ENABLE_X64: True
