name: Tests
on:
  push:
    paths:
      - PyCO2SYS/**
      - tests/**
      - pyproject.toml
      - pytest.ini
      - .github/workflows/python-package.yml
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v4
        with:
          auto-activate: false
      - name: Create conda environment
        run: |
          conda create -n pyco2sys -c conda-forge python=${{ matrix.python-version }} pygraphviz pip
      - name: Install pip dependencies
        run: |
          conda activate pyco2sys
          pip install pytest xarray pandas openpyxl matplotlib
          pip install .
      - name: Test with pytest
        run: |
          conda activate pyco2sys
          pytest
        env:
          JAX_ENABLE_X64: True
