name: Tests
on:
  push:
    paths:
      - PyCO2SYS/**
      - tests/**
      - pyproject.toml
      - pytest.ini
      - .github/workflows/python-package.yml
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest xarray pandas openpyxl matplotlib
          pip install .
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v4.0.1
      - name: Install conda dependencies
        run: |
          conda install pygraphviz
      - name: Test with pytest
        run: |
          pytest
        env:
          JAX_ENABLE_X64: True
