pHx = 8;
TCx = 2100e-6;
K1 = 1;
K2 = 2;
KW = 3;
KB = 4;
KF = 5;
KS = 6;
KP1 = 7;
KP2 = 8;
KP3 = 9;
KSi = 10;
TB = 400e-6;
TF = 10e-6;
TS = 2000e-6;
TP = 10e-6;
TSi = 50e-6;

H         = 10.^(-pHx);
HCO3      = TCx.*K1.*H  ./(K1.*H + H.*H + K1.*K2);
CO3       = TCx.*K1.*K2./(K1.*H + H.*H + K1.*K2);
BAlk      = TB.*KB./(KB + H);
OH        = KW./H;
PhosTop   = KP1.*KP2.*H + 2.*KP1.*KP2.*KP3 - H.*H.*H;
PhosBot   = H.*H.*H + KP1.*H.*H + KP1.*KP2.*H + KP1.*KP2.*KP3;
PAlk      = TP.*PhosTop./PhosBot;
% this is good to better than .0006*TP:
% PAlk = TP*(-H/(KP1+H) + KP2/(KP2+H) + KP3/(KP3+H))
SiAlk     = TSi.*KSi./(KSi + H);
FREEtoTOT = (1 + TS./KS);        %' pH scale conversion factor
Hfree     = H./FREEtoTOT;          %' for H on the total scale
HSO4      = TS./(1 + KS./Hfree); %' since KS is on the free scale
HF        = TF./(1 + KF./Hfree); %' since KF is on the free scale
